# Generated by Django 3.0.2 on 2020-01-14 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200105_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=16, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 14, 6, 20, 35, 786286, tzinfo=utc), null=True)),
                ('article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
    ]
