# Generated by Django 3.0.2 on 2020-01-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200118_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created']},
        ),
    ]
